/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/**
 *
 * @author Roy Morocho <roymorocho at gmail.com>
 */
public class VPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form V_PRINCIPAL
     */
    public VPrincipal() {
        initComponents();
//        cerrar();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dtp_principal = new javax.swing.JDesktopPane();
        lbl_user_name = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jmb_general = new javax.swing.JMenuBar();
        jm_mantenimiento = new javax.swing.JMenu();
        ItemUsuario = new javax.swing.JMenuItem();
        ItemEmpleado = new javax.swing.JMenuItem();
        itemVehiculos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        item_logout = new javax.swing.JMenuItem();
        Item_salir = new javax.swing.JMenuItem();
        jm_consultas = new javax.swing.JMenu();
        Citem_usuario = new javax.swing.JMenuItem();
        Citem_trabajadores = new javax.swing.JMenuItem();
        Citem_vehiculos = new javax.swing.JMenuItem();
        jm_reportes = new javax.swing.JMenu();
        Ritem_clientes = new javax.swing.JMenuItem();
        Ritem_empleado = new javax.swing.JMenuItem();
        jm_info = new javax.swing.JMenu();
        jmi_about = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dtp_principal.setBackground(new java.awt.Color(230, 235, 240));
        dtp_principal.setForeground(new java.awt.Color(230, 235, 240));
        dtp_principal.setToolTipText("");
        dtp_principal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dtp_principal.setDesktopManager(null);

        javax.swing.GroupLayout dtp_principalLayout = new javax.swing.GroupLayout(dtp_principal);
        dtp_principal.setLayout(dtp_principalLayout);
        dtp_principalLayout.setHorizontalGroup(
            dtp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
        );
        dtp_principalLayout.setVerticalGroup(
            dtp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 663, Short.MAX_VALUE)
        );

        lbl_user_name.setBackground(new java.awt.Color(255, 255, 255));
        lbl_user_name.setForeground(new java.awt.Color(44, 73, 114));
        lbl_user_name.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbl_user_name.setToolTipText("");
        lbl_user_name.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        jLabel2.setText("Open camera");

        jmb_general.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.background"));

        jm_mantenimiento.setBackground(java.awt.Color.darkGray);
        jm_mantenimiento.setForeground(new java.awt.Color(255, 255, 255));
        jm_mantenimiento.setText("Mantenimiento");
        jm_mantenimiento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jm_mantenimiento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        ItemUsuario.setBackground(java.awt.Color.darkGray);
        ItemUsuario.setForeground(new java.awt.Color(255, 255, 255));
        ItemUsuario.setText("Nuevo usuario");
        ItemUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemUsuarioActionPerformed(evt);
            }
        });
        jm_mantenimiento.add(ItemUsuario);
        ItemUsuario.getAccessibleContext().setAccessibleParent(jm_mantenimiento);

        ItemEmpleado.setBackground(java.awt.Color.darkGray);
        ItemEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        ItemEmpleado.setText("Nuevo Empleado");
        jm_mantenimiento.add(ItemEmpleado);
        ItemEmpleado.getAccessibleContext().setAccessibleParent(jm_mantenimiento);

        itemVehiculos.setText("Vehiculos");
        jm_mantenimiento.add(itemVehiculos);

        jSeparator1.setBackground(java.awt.Color.darkGray);
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jm_mantenimiento.add(jSeparator1);

        item_logout.setBackground(java.awt.Color.darkGray);
        item_logout.setForeground(new java.awt.Color(255, 255, 255));
        item_logout.setText("Cerrar sesión");
        item_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_logoutActionPerformed(evt);
            }
        });
        jm_mantenimiento.add(item_logout);
        item_logout.getAccessibleContext().setAccessibleParent(jm_mantenimiento);

        Item_salir.setBackground(java.awt.Color.darkGray);
        Item_salir.setForeground(new java.awt.Color(255, 255, 255));
        Item_salir.setText("Salir");
        jm_mantenimiento.add(Item_salir);
        Item_salir.getAccessibleContext().setAccessibleParent(jm_mantenimiento);

        jmb_general.add(jm_mantenimiento);

        jm_consultas.setBackground(java.awt.Color.darkGray);
        jm_consultas.setForeground(new java.awt.Color(255, 255, 255));
        jm_consultas.setText("Consultas");

        Citem_usuario.setBackground(java.awt.Color.darkGray);
        Citem_usuario.setForeground(new java.awt.Color(255, 255, 255));
        Citem_usuario.setText("Usuarios");
        Citem_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Citem_usuarioActionPerformed(evt);
            }
        });
        jm_consultas.add(Citem_usuario);

        Citem_trabajadores.setBackground(java.awt.Color.darkGray);
        Citem_trabajadores.setForeground(new java.awt.Color(255, 255, 255));
        Citem_trabajadores.setText("Empleados");
        Citem_trabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Citem_trabajadoresActionPerformed(evt);
            }
        });
        jm_consultas.add(Citem_trabajadores);

        Citem_vehiculos.setBackground(java.awt.Color.darkGray);
        Citem_vehiculos.setForeground(new java.awt.Color(255, 255, 255));
        Citem_vehiculos.setText("Vehículos");
        jm_consultas.add(Citem_vehiculos);

        jmb_general.add(jm_consultas);

        jm_reportes.setBackground(java.awt.Color.darkGray);
        jm_reportes.setForeground(new java.awt.Color(255, 255, 255));
        jm_reportes.setText("Reportes");

        Ritem_clientes.setBackground(java.awt.Color.darkGray);
        Ritem_clientes.setForeground(new java.awt.Color(255, 255, 255));
        Ritem_clientes.setText("Clientes");
        jm_reportes.add(Ritem_clientes);

        Ritem_empleado.setBackground(java.awt.Color.darkGray);
        Ritem_empleado.setForeground(new java.awt.Color(255, 255, 255));
        Ritem_empleado.setText("Empleados");
        Ritem_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ritem_empleadoActionPerformed(evt);
            }
        });
        jm_reportes.add(Ritem_empleado);

        jmb_general.add(jm_reportes);

        jm_info.setBackground(java.awt.Color.darkGray);
        jm_info.setForeground(new java.awt.Color(255, 255, 255));
        jm_info.setText("Info");

        jmi_about.setBackground(java.awt.Color.darkGray);
        jmi_about.setForeground(new java.awt.Color(255, 255, 255));
        jmi_about.setText("About");
        jm_info.add(jmi_about);

        jmb_general.add(jm_info);

        setJMenuBar(jmb_general);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dtp_principal)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(637, 637, 637)
                .addComponent(lbl_user_name, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dtp_principal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_user_name, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemUsuarioActionPerformed

    private void item_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_logoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item_logoutActionPerformed

    private void Ritem_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ritem_empleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ritem_empleadoActionPerformed

    private void Citem_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Citem_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Citem_usuarioActionPerformed

    private void Citem_trabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Citem_trabajadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Citem_trabajadoresActionPerformed

    public JDesktopPane getDtp_principal() {
        return dtp_principal;
    }

    public JMenu getJm_info() {
        return jm_info;
    }

    public JMenuItem getItemVehiculos() {
        return itemVehiculos;
    }

    public void setItemVehiculos(JMenuItem itemVehiculos) {
        this.itemVehiculos = itemVehiculos;
    }
    
    public void setJm_info(JMenu jm_info) {
        this.jm_info = jm_info;
    }

    public JMenuItem getJmi_about() {
        return jmi_about;
    }

    public JLabel getLbl_user_name() {
        return lbl_user_name;
    }

    public void setLbl_user_name(JLabel lbl_user_name) {
        this.lbl_user_name = lbl_user_name;
    }
    

    public void setJmi_about(JMenuItem jmi_about) {
        this.jmi_about = jmi_about;
    }
    

    public void setDtp_principal(JDesktopPane dtp_principal) {
        this.dtp_principal = dtp_principal;
    }

    public JMenuItem getItemUsuario() {
        return ItemUsuario;
    }

    public void setItemUsuario(JMenuItem ItemUsuario) {
        this.ItemUsuario = ItemUsuario;
    }

    public JMenuItem getItemEmpleado() {
        return ItemEmpleado;
    }

    public void setItemEmpleado(JMenuItem ItemEmpleado) {
        this.ItemEmpleado = ItemEmpleado;
    }


    public JMenuItem getCitem_trabajadores() {
        return Citem_trabajadores;
    }

    public JMenuItem getRitem_clientes() {
        return Ritem_clientes;
    }

    public void setRitem_clientes(JMenuItem Ritem_clientes) {
        this.Ritem_clientes = Ritem_clientes;
    }

    public JMenuItem getRitem_empleado() {
        return Ritem_empleado;
    }

    public void setRitem_empleado(JMenuItem Ritem_empleado) {
        this.Ritem_empleado = Ritem_empleado;
    }
    

    public void setCitem_trabajadores(JMenuItem Citem_trabajadores) {
        this.Citem_trabajadores = Citem_trabajadores;
    }

    public JMenuItem getCitem_usuario() {
        return Citem_usuario;
    }

    public void setCitem_usuario(JMenuItem Citem_usuario) {
        this.Citem_usuario = Citem_usuario;
    }

    public JMenuItem getCitem_vehiculos() {
        return Citem_vehiculos;
    }

    public void setCitem_vehiculos(JMenuItem Citem_vehiculos) {
        this.Citem_vehiculos = Citem_vehiculos;
    }

    public JMenuItem getItem_salir() {
        return Item_salir;
    }

    public void setItem_salir(JMenuItem Item_salir) {
        this.Item_salir = Item_salir;
    }

    public JMenuItem getItem_logout() {
        return item_logout;
    }

    public JMenuBar getJmb_general() {
        return jmb_general;
    }

    public void setJmb_general(JMenuBar jmb_general) {
        this.jmb_general = jmb_general;
    }
    

    public void setItem_logout(JMenuItem item_logout) {
        this.item_logout = item_logout;
    }

//    
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VPrincipal().setVisible(true);
//            }
//        });
//    public void cerrar(){
//        try {
//            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
//            addWindowListener(new WindowAdapter() {
//                public void windowClosing(WindowEvent e){
//                    JOptionPane.showMessageDialog(null, "Debe cerrar Sesion");
//                }            
//            });
//            this.setVisible(true);
//        } catch (Exception e) {
//        }
//    }
    public JMenu getJm_consultas() {
        return jm_consultas;
    }

    public void setJm_consultas(JMenu jm_consultas) {
        this.jm_consultas = jm_consultas;
    }

    public JMenu getJm_mantenimiento() {
        return jm_mantenimiento;
    }

    public void setJm_mantenimiento(JMenu jm_mantenimiento) {
        this.jm_mantenimiento = jm_mantenimiento;
    }

    public JMenu getJm_reportes() {
        return jm_reportes;
    }

    public void setJm_reportes(JMenu jm_reportes) {
        this.jm_reportes = jm_reportes;
    }
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Citem_trabajadores;
    private javax.swing.JMenuItem Citem_usuario;
    private javax.swing.JMenuItem Citem_vehiculos;
    private javax.swing.JMenuItem ItemEmpleado;
    private javax.swing.JMenuItem ItemUsuario;
    private javax.swing.JMenuItem Item_salir;
    private javax.swing.JMenuItem Ritem_clientes;
    private javax.swing.JMenuItem Ritem_empleado;
    private javax.swing.JDesktopPane dtp_principal;
    private javax.swing.JMenuItem itemVehiculos;
    private javax.swing.JMenuItem item_logout;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu jm_consultas;
    private javax.swing.JMenu jm_info;
    private javax.swing.JMenu jm_mantenimiento;
    private javax.swing.JMenu jm_reportes;
    private javax.swing.JMenuBar jmb_general;
    private javax.swing.JMenuItem jmi_about;
    private javax.swing.JLabel lbl_user_name;
    // End of variables declaration//GEN-END:variables
}
